language: python
dist: xenial
python:
- 2.7
- 3.5
- 3.6
- 3.7
install:
- pip install pipenv
- pipenv install --dev --skip-lock --python `which python`
- pipenv graph
script: pipenv run py.test -v
before_deploy:
- sed -i.bak "s/=get_version()/='$TRAVIS_TAG'/g" setup.py
- cat setup.py
- if [ $(python setup.py --version) == '0.0.0' ]; then travis_terminate 1; fi
deploy:
  provider: pypi
  user: uc-ctds
  skip_existing: true
  skip_cleanup: true
  on:
    python: 2.7
    repo: uc-cdis/cdislogging
    tags: true
  password:
    secure: o3Nizw9Jjbf2SBA2kE+7e08ZW0YTbshmYXHTS3+YAedfBlFyj78tH6+O3mnuWFsbNJKhMMwLYdOX0CMtVPjXg91wWyxZT9OLTCUqNYq9+K69ruDyJHM7QWKsLmLqCe4xVMQYxvlpJkZHHprfF3wXI9v3s0OV+Z+bAf9cAvW/dCcrXPsmRKeg94Whjj+MCDY58IG8mPIAvEMOoX6LEVqZVwagLGaIxkcQCbt+Zp8O72l3puex+x9wiqF0XawD3JdIMr7xf/xoEhuG7w697rnvHCEjW/48yKPXMwt/9/OV1ZQI3PVb6QxxsMAHB8UvQS/h4DtCh8OfZwchxB6MUwilnXHQjMd+diGCjOkk9G0ZBJuYb/Az9Z6YRGF+22qmcPC84KwOMoAY21sPQIuPHNDdug+HBXq07E5ZLmjBUvjVADN3ooLpXHswlOm3tYsnbStZox1+lqxCm2Z2f5v/Mz4C1IfWxtHFmM4U5UkDTQOu0K/C3NvEneKJrsN5Bd0/Cj1se3HYJgAhH0K1US5m8H7Vgejr9vIVSapa4QcTn3ZbeW/m1df2JXGG5cammbxXKxN4ErZq51j5hmp3yIL7H0Ohjnb9eTvsWDVtFL8FwrR8YbCFndF/2bsLlu860NTjaIz0P3pLizpd7hUZgh4+BCtvrt30x/HaelSmphja07EdlIg=
env:
  global:
  - PIPENV_IGNORE_VIRTUALENVS=1
  - secure: uovNV8i+Ef7EbSGaeGKvlm168nsuP6XF6p/ERlRQZtZ9HQBF14IVlqYnLgBvFGVdFsIc1mCroKqfdIiJIy75Bx1YOvO+u/3mxjMlOxuqxNCbIK0bYxZhrLqbR1oXGk6yPALpaeBdtuf43tnux0Ajk4URg2mIfqySkVldQPzL5XUfH/ueIruz6y5/alt7+c1Uj7HblGVBJbHx6JKGJSjpknfJyZXirw/lXpcFgOmRFjijGo4vYqmHIppGhERCCLNXdOTbrqe5dnbb8AD2AZwRDkgluYAYWaaJr9VosKzqD1lUfBVAbV91noCb+Nf91wfhzZemRWSy0xgIAPrpaT5QUm1OtJ1Z9J7yjD7Ljlt+CT5xHOE1uquKRXKzWpv4q1lHGyqyePKKHIcslu4gu1H8BO1EF212doQJFuPE68xEuSrVpZ0r2EKIYCgGfuto3AXWQzriD9uBQpqaVCNVjUkRVTa8t8G4WVLr3SeYSsY97CNASShJ9QiAshPogPv+FA+JM4JL0gyfrSCsaW2YtU1ovFv0ppP9KHtWzIZPEqZdMI8EUK4ugse94c2inzRJCTmE8j2K2J9sZS9i0jhTOnuL9mviXzr5goopmAYYhF1OWNV0KTDcxHnXSmWZR3HQP35aPFGZzjc0HLN/8khPb+P4mJ/XZfL+RtaQzJIYJ08TY6c=
after_deploy:
- pipenv run pip install gen3git
- pipenv run gen3git release
